[project]
name = "osm-automated-edits"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "osm-bot-abstraction-layer>=0.0.22",
]
